name: Build

on:
  push:
    branches:
      - main
  pull_request: ~

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: actions/setup-python@v6.2.0
        with:
          python-version: '~3.12.7'
          check-latest: true
      - run: ./scripts/build.sh platformer 0.0.0
      - uses: actions/upload-artifact@v7.0.1
        with:
          path: output/*.apworld
          archive: false
          if-no-files-found: error
      - name: Install archipelago
        run: |
          curl \
            --fail \
            --location \
            --output /usr/local/bin/archipelago \
            https://github.com/ArchipelagoMW/Archipelago/releases/download/0.6.7/Archipelago_0.6.7_linux-x86_64.AppImage

          echo "6b951acf3a86bbbab8660d406079db42309340d75c35a2ff819523615dd19394 /usr/local/bin/archipelago" | sha256sum --check -

          chmod +x /usr/local/bin/archipelago

          mkdir --parents ~/.local/share/Archipelago/worlds/

          echo "ARCHIPELAGO_USER_PATH=$HOME/.local/share/Archipelago/" >> "$GITHUB_ENV"
      - name: Install apworld
        run: cp output/*.apworld ~/.local/share/Archipelago/worlds/
      - name: Generate template
        run: archipelago 'Generate Template Options' -- --skip_open_folder
      - uses: actions/upload-artifact@v7.0.1
        with:
          path: ${{ env.ARCHIPELAGO_USER_PATH }}/Players/Templates/Factorio Platformer.yaml
          archive: false
          if-no-files-found: error
      - name: Test generation
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          cp "$ARCHIPELAGO_USER_PATH/Players/Templates/Factorio Platformer.yaml" "$ARCHIPELAGO_USER_PATH/Players/"

          archipelago --executable ArchipelagoGenerate --seed 0
